import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "@/components/ui/provider";
import { ptBR } from "date-fns/locale";
import { setDefaultOptions } from "date-fns";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

setDefaultOptions({ locale: ptBR });

export default function RootLayout(props: { children: React.ReactNode }) {
  const { children } = props;
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
